[package]
name = "jito-protos"
version = "1.10.40"
edition = "2021"
publish = false

[dependencies]
crossbeam-epoch = "=0.9.5" # TODO (LB): this allows compliation on rust_nightly in ci
lock_api = "=0.4.6" # TODO (LB): this allows compliation on rust_nightly in ci
prost = "0.10.0"
prost-types = "0.10.0"
tonic = "=0.7.1"

[build-dependencies]
tonic-build = "=0.7.1"
